goodwithtech/dockle

- pkg/assessor/manifest/manifest.go
GPG_KEY is used in official images.
https://github.com/docker-library/python/blob/34c9df35e9a69e9f0edde88e861b543edb8bc07a/3.7/alpine3.8/Dockerfile#L20
> Accept GPG_KEY

- pkg/run.go
Ignore the following warning
```
2019-06-07T13:23:07.747+0900    WARN    A new version v0.0.15 is now available! You have vdev.
```
> Ignore dev version

- .circleci/config.yml
- Test should run on all branches/tags. So the filter is not really needed...
- release process already has the `only` annotation on tag so it should ignore any branches without `ignore`.
- Add new line at EOF for POSIX compatibility.
- Ref
- http://hiroakiuno.hatenablog.com/entry/20070409/p1
- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
> modify ci config

- pkg/assessor/privilege/suid.go
The output looks cleaner (file modes are more probably fixed-width)
and is in line with the output of `stat -c '%A %n'` and `ls -l`.
> suid: Print file mode left of file name

- pkg/report/writer.go
According to the SARIF Standard section 3.27.10, `warning` should be used instead of `warn`
> Fix SARIF label for warn level

- README.md
ERROR:
 $ VERSION=$(
curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
grep '"tag_name":' | \
sed -E 's/.*"v([^"]+)".*/\1/' \
) && rpm -ivh https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.rpm
**bash: $: command not found...**
> install on Linux fails copy & paste from git UI

- README.md
The [asdf version manager](https://asdf-vm.com/) is a tool for installing release binaries from github. I have created an installation plugin for dockle:
https://github.com/mathew-fleisch/asdf-dockle
Let me know if I can do anything else for this PR.
Thanks! Cool tool!
> Add asdf installation instructions to read-me

- README.md
Add dockle package
Improve installation section
AUR helpers are not the correct way and should not be suggested:
Read first line of https://wiki.archlinux.org/title/AUR_helpers
> Arch Linux: Improve installation section

- cmd/dockle/main.go
When consuming Dockle as a go module, there is currently no way of running it easily.
The introduction of a public "Dockle CLI creator" will enable that
> Add the option to run Dockle programmatically

- README.md
Fix several typos in the documentation
> docs: fix several typos

- cmd/dockle/main.go
- pkg/run.go
Fixes #170
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
> feat: accept docker daemon host via flag

- cmd/dockle/main.go
- pkg/run.go
Add a cert-path parameter to allow private docker certs for tcp connections.
https://github.com/goodwithtech/dockle/issues/175
> Add docker tcp certificate path. Issue #175

- pkg/utils/fetch.go
```
INFO    Failed to check latest version. not found version patterns
```
In Dockle v0.4.5, the above error occurs.
Therefore, I modify the fetch for the latest version to get the location in the response at　https://github.com/goodwithtech/dockle/releases/latest .
> Fix fetch of latest version

- CHECKPOINT.md
I couldn't find your contribution guide line and I just opened a pull request.
Sorry if I'm doing something wrong.
It's really minor documentation thing, but isn't it `g-s` instead of `u-g` ?
Also, I appreciate your great work!
> fix command of removing setgid permission

- README.md
These are the necessary instructions for downloading Dockle for Windows 64bit using Microsoft PowerShell 7 (which is slightly different from "Windows PowerShell 5" - MS PowerShell is the newest version)
> Add instructions for Microsoft PowerShell

- pkg/utils/fetch.go
https://github.com/goodwithtech/dockle/runs/7367330171?check_suite_focus=true
```
Error: pkg/utils/fetch.go:55:84: cannot convert body (type *string) to type string
```
A return value of `fetchLocation` is `*string`. Therefore, I avoid casting it as a `string`.
> Avoid casting the result of fetchLocation

- go.mod
- go.sum
- pkg/app.go
- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
- pkg/run.go
Add check for sensitive variable names in commands history.
Add unit tests.
Add cli flag for adding sensitive keys to look for.
> pkg/assessor/manifest: Add sensitive variable names checks

- go.mod
- go.sum
refs: https://avd.aquasec.com/nvd/cve-2022-39237
Hi!
thanks for provide great product!
github.com/sylabs/sif/v2 is affected CVE-2022-39237 and then I update it.
thanks!
> update github.com/sylabs/sif/v2 for CVE-2022-39237

- go.mod
- go.sum
```
go get go.etcd.io/bbolt@v1.3.7 && go mod tidy
GOOS="linux" GOARCH="loong64" go build ./cmd/dockle/main.go
```
> add loong64 build support

- CHECKPOINT.md
- pkg/assessor/cache/cache.go
- Update suspicious directories to include cloud-specific configuration directories
- Add `.DS_Store` file to unnecessary files:
A .DS_Store, short for Desktop Services Store, is an invisible file on the macOS operating system that gets automatically created anytime you look into a folder with ‘Finder.’ This file will then follow the folder everywhere it goes, including when archived, like in ‘ZIP.’
If you’re a developer or system administrator and still transferring files from your computer to your server or don’t take the necessary precautions with your automated deployment process, you could be putting these files on the server where your site or application lives unconsciously.
> Remove `tmp/` as a Suspicious Directory and Include Cloud Specific Configuration Files

- goreleaser.yaml
I'm not sure to add build support for "nfpms", because there is currently no stable distribution operating system available.
> add archives release for loong64

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
This pull request intends to censor suspicious found environment variables.
Previously any suspicious environment variable found was being leaked during `CIS-DI-0010` checkpoint assessment as seen below:
```
FATAL   - CIS-DI-0010: Do not store credential in environment variables/files
* Suspicious ENV key found : GITLAB_TOKEN on /bin/sh -c #(nop)  ENV GITLAB_TOKEN=y5V1xiW5eTwq34jasRqFBD (You can suppress it with --accept-key)
```
With this PR the same finding would be:
```
FATAL   - CIS-DI-0010: Do not store credential in environment variables/files
* Suspicious ENV key found : GITLAB_TOKEN on /bin/sh -c #(nop)  ENV GITLAB_TOKEN=******* (You can suppress it with --accept-key)
```
Notice that the environment variable now isn't leaked on the output to stdout. This also applies to any other …
> Censor suspicious environment variables

- README.md
- pkg/app.go
- pkg/assessor/credential/credential.go
- pkg/run.go
Added new parameters for suspicious files or file extensions for checkpoint `CIS-DI-0010`:
- `--sensitive-file` / `--sf` / `DOCKLE_REJECT_FILES` - Add suspicious files to look for
- `--sensitive-file-extension` / `--se` / `DOCKLE_REJECT_FILE_EXTENSIONS` - Add suspicious file extensions to look for
Also updated README.md with documentation regarding already existing `--sensitive-word`
Fixes #265
> Add parameters for sensitive files and sensitive file extensions
