- pkg/types/checkpoint.go
- pkg/writer/writer.go
> Display code

- pkg/run.go
- pkg/types/checkpoint.go
- pkg/writer/writer.go
> Ignore checkpoints even if exit code is zero

- README.md
- pkg/assessor/manifest/manifest.go
https://github.com/goodwithtech/dockle/issues/13
> fix CIS-DI-0007

- .dockerignore
- README.md
- cmd/dockle/main.go
- pkg/report/json.go
- pkg/report/list.go
- pkg/report/writer.go
- pkg/run.go
for https://github.com/goodwithtech/dockle/issues/24
> support json format

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
- pkg/assessor/manifest/testdata/apk_cache.json
Fix fo https://github.com/goodwithtech/dockle/issues/41
target format : `ADD xxxxx in /xxx`
> fix ADD statement condition

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
dist-upgrade only checks apt-get, apt and apk
> fix dist upgrade statement

- README.md
I maintained the packages in Arch Linux User Repository
> Adding instructions for Install in Arch Linux

- CHECKPOINT.md
- pkg/assessor/manifest/manifest.go
> ease sinsitive dir rules

- pkg/assessor/cache/cache.go
> fix: correct printout typo

- CHECKPOINT.md
- README.md
- go.mod
- go.sum
- pkg/assessor/contentTrust/contentTrust.go
- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
- pkg/assessor/privilege/suid.go
- pkg/scanner/scan_test.go
- pkg/scanner/testdata/Dockerfile.base
- pkg/types/checkpoint.go
for https://github.com/goodwithtech/dockle/issues/55
- check setuid/seguid in any paths
- changed message for CIS-DI-0008
> check permissions in any dir

- Dockerfile
> update Docker image

- .github/workflows/build-scan-on-push.yml
- .github/workflows/main.yml
- Dockerfile
add github action Scan the target image with trivy
and update alpine in Dockerfile to 3.12
> add Scan the target image with trivy

- goreleaser.yaml
- pkg/run.go
https://github.com/goodwithtech/dockle/issues/88
> bugfix: use insecure flag

- cmd/dockle/main.go
https://github.com/goodwithtech/dockle/issues/106
> bugfix: read user/pass from environment variables

- pkg/utils/fetch.go
ref: https://github.com/goodwithtech/dockle/issues/111
> check latest versions follows latest github release page

- pkg/run.go
> fix latest bug

- Dockerfile
- Dockerfile.releaser
- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
> buildkit: check ADD statements 

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
- pkg/assessor/manifest/testdata/apt_update_upgrade.json
https://github.com/goodwithtech/dockle/issues/128
> allow apt(-get) update && upgrade

- pkg/utils/fetch.go
> not follow redirects when a client checks version

- cmd/dockle/main.go
- pkg/log/logger.go
- pkg/run.go
> implement quiet mode

- cmd/dockle/main.go
- pkg/report/list.go
- pkg/run.go
> add no-color option

- cmd/dockle/main.go
- pkg/run.go
> enhanced error message

- pkg/run.go
- pkg/types/assessment.go
- pkg/types/assessment_test.go
> IGNORE level results only show in debug mode

- cmd/dockle/main.go
- pkg/assessor/manifest/manifest.go
- pkg/run.go
> add options: accept-key

- README.md
- cmd/dockle/main.go
- pkg/assessor/assessor.go
- pkg/assessor/cache/cache.go
- pkg/assessor/contentTrust/contentTrust.go
- pkg/assessor/credential/credential.go
- pkg/assessor/group/group.go
- pkg/assessor/hosts/hosts.go
- pkg/assessor/manifest/manifest.go
- pkg/assessor/passwd/passwd.go
- pkg/assessor/privilege/suid.go
- pkg/assessor/user/user.go
- pkg/run.go
- pkg/scanner/scan.go
- pkg/scanner/scan_test.go
* check with file extension names
* add --accept-file, --accept-file-extension option
> check suspitious file extensions and add suspitious filenames

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
> bugfix: DKL-DI-0005 false positive #151

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
Dockle consider commands order when checking a manifest.
> apt command validator consider commands order

- pkg/assessor/credential/credential.go
- pkg/scanner/scan_test.go
- pkg/types/checkpoint.go
> remove pem file from sensitive file extensions

- go.mod
- go.sum
- pkg/report/sarif.go
Admittedly this PR isn't going to change much in real terms for the usage of the library here, but updating to v2 opens up the potential to write fuller SARIF report.
Appreciate if you chose to stick with v1 if its working for you - I just wanted to make you aware v2 was much more comprehensive :+1:
> [chore] Update go-sarif version

- pkg/app.go
- pkg/run.go
> add use-xdg option

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
> env key should not contain space

- pkg/report/sarif_test.go
- pkg/report/testdata/DKL-DI-0006.sarif
- pkg/run.go
> remove docker scheme from filename

- README.md
Noticed the license listed in the README was wrong...
> Update README to fix wrong license listing

- pkg/assessor/manifest/manifest.go
- pkg/assessor/manifest/manifest_test.go
- pkg/assessor/manifest/testdata/add_with_arg_statement.json
- pkg/assessor/manifest/testdata/multi_add.json
https://github.com/goodwithtech/dockle/issues/228
https://github.com/goodwithtech/dockle/issues/220
https://github.com/goodwithtech/dockle/issues/217
https://github.com/goodwithtech/dockle/issues/218
> allow first add statement in config files

- pkg/assessor/passwd/passwd.go
https://github.com/goodwithtech/dockle/issues/225
> check password format in Password assessor

- goreleaser.yaml
https://github.com/goreleaser/goreleaser/blob/3e03fea974104470aedff528075fc38ece201fff/www/docs/deprecations.md?plain=1#L338-L413
> update goreleaser format

- pkg/assessor/credential/credential.go
> Conflict Resolved: Add .env file to suspicious files list #266
